EMBEDDING_MODEL:
  REPO_ID: "lier007/xiaobu-embedding-v2"
  EMBEDDING_MODEL_NAME: "xiaobu-embedding-v2"
  EMBEDDING_MODEL_PATH: "models/embeddings/xiaobu-embedding-v2"
DATASET:
  NPZ_FILE: "dataset/tang.npz"